### ISSUE TITLE
Add velocity support

### ISSUE THREAD

**Issue by AnghiYt** [andrei1058/BedWarsProxy#50]
Please, add support of velocity in this plugin

**Comment by JT122406** [comment]
What does that mean?

**Comment by JT122406** [comment]
Velocity is supported

**Comment by JT122406** [comment]
I currently use it on a velocity server nothing runs on the proxy only on backend

**Comment by AnghiYt** [comment]
Oh ok. I just took a look at the code and there didn't seem to be any references to velocity

**Comment by JT122406** [comment]
yeah because its run only on backend

**Comment by skbeh** [comment]
Velocity plugins usually have their own message channels, such as this: https://github.com/MTM123/AuthMeVelocity/commit/9471a1a2ecddfe625400adb600e66097ca5b013a

**Comment by skbeh** [comment]
@JT122406 Velocity plugins usually use their own message channels, such as this: https://github.com/MTM123/AuthMeVelocity/commit/9471a1a2ecddfe625400adb600e66097ca5b013a

**Comment by JT122406** [comment]
This doesn’t use any thing on the bungee/velocity side only on the spigot side

**Comment by skbeh** [comment]
@JT122406 I got it. By the way, it would be better to allow setting bind address so that the socket can be bound to localhost to enhance security, or support Unix socket.
